services:
  librechat_api:
    image: ghcr.io/gradient-ds/neo-soevai-api:${LIBRECHAT_TAG:-latest}
    # build:
    #   context: .
    #   dockerfile: Dockerfile.soev.ai.multi
    #   target: api-build
    container_name: librechat_api
    restart: unless-stopped
    labels:
      - "soevai.restart=enabled"
    environment:
      CONFIG_PATH: /app/librechat.soev.ai.yaml
      BASE_CONFIG_PATH: /app/librechat.soev.ai.yaml
      HOST: 0.0.0.0
      PORT: 3080
      MONGO_URI: mongodb://mongodb:27017/LibreChat
      MEILI_HOST: http://meilisearch:7700
      RAG_API_URL: http://rag_api:8000
      SOEVAI_ROOT: /app
    depends_on:
      - mongodb
      - rag_api
    env_file:
      - .env
    volumes:
      - ./librechat.yaml:/app/librechat.yaml:ro
      - ./librechat.soev.ai.yaml:/app/librechat.soev.ai.yaml:rw
      - ./admin-overrides.yaml:/app/admin-overrides.yaml:rw
      - ./uploads:/app/uploads
      - ./logs:/app/api/logs
    ports:
      - "3080:3080"

  mongodb:
    image: mongo
    container_name: prod-mongodb
    restart: unless-stopped
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth

  meilisearch:
    image: getmeili/meilisearch:v1.12.3
    container_name: prod-meilisearch
    restart: unless-stopped
    environment:
      MEILI_NO_ANALYTICS: "true"
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    volumes:
      - ./meili_data_v1.12:/meili_data

  vectordb:
    image: ankane/pgvector:latest
    container_name: prod-vectordb
    restart: unless-stopped
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata2:/var/lib/postgresql/data

  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev:latest
    container_name: dev-rag-api
    restart: unless-stopped
    depends_on:
      - vectordb
    environment:
      DB_HOST: vectordb
      RAG_PORT: 8000
      # EMBEDDINGS_PROVIDER: openai
      OPENAI_API_KEY: ${UBIOPS_RAG_1}
      OPENAI_BASE_URL: ${RAG_OPENAI_BASE_URL}
      EMBEDDINGS_MODEL: ${RAG_EMBEDDINGS_MODEL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      RAG_CHECK_EMBEDDING_CTX_LENGTH: false
    env_file:
      - .env
    ports:
      - "8000:8000"
  

volumes:
  pgdata2:
  # ollama: 